name: RaidCraftRCRegions
main: com.silthus.rcregions.bukkit.RCRegionsPlugin
version: 0.1
author: Silthus
website: www.raid-craft.de
depend: [RaidCraft,WorldGuard]
softdepend: [Register]
load: POSTWORLD

permissions:
  rcregions.*:
    description: Gives access to all Inferno commands
    children:
      rcregions.sign.create: true
  rcregions.sign.create:
    description: Allows you to sell regions via signs
    default: true