name: RCRegions
version: 0.1
author: Silthus
website: www.raid-craft.de

main: com.raidcraft.rcregions.bukkit.RegionsPlugin
depend: [RaidCraftCore,WorldGuard]

commands:
  rcr:
    description: Gives acces to the RCRegions plugin.
    usage: Please see the help with /<command> help.
    aliases: [plot]
permissions:
  rcregions.user:
      description: Gives access to basic Region commands.
      default: op
      children:
        rcregions.region.buy: true
        rcregions.sign.place: true
        rcregions.region.drop: true
        rcregions.region.sell: true
  rcregions.region.buy:
      default: op
  rcregions.region.drop:
        default: op
  rcregions.sign.place:
      default: op
  rcregions.region.sell:
      default: op
  rcregions.admin:
      default: op
  rcregions.region.warp:
      default: op
  rcregions.warn:
      default: op