name: RCRegions
version: 0.1
author: Silthus
website: www.raid-craft.de

main: de.raidcraft.rcregions.bukkit.RegionsPlugin
database: true
depend: [RaidCraftCore,WorldGuard]

commands:
  rcr:
    description: Gives acces to the RCRegions plugin.
    usage: Please see the help with /<command> help.